# Generated by Django 2.0.3 on 2018-04-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=300)),
                ('article_text', models.CharField(max_length=5000)),
                ('create_time', models.DateTimeField(verbose_name=True)),
                ('update_time', models.DateTimeField(verbose_name=True)),
            ],
        ),
    ]
